name: misshakim.onlime build

on:
  workflow_dispatch:
  schedule:
  - cron: "00 07,09 * * *"  
# env:
#   TZ: "IST"
  
jobs:
  build:
    runs-on: self-hosted
    name: find-games-and-update-db
    steps:

      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build with Maven
        run: mvn -B package --file pom.xml


  send-email:
    runs-on: self-hosted
    name: send-email
    steps:
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: misshakim.onlinme delpoy
          # email body as text
          body: misshakim.onlinme delpoy
          # comma-separated string, send email to
          to: soul3510@gmail.commisshakim.onlinme delpoy
          # from email name
          from: Eyal Sooliman
