name: misshakim.onlime build

on:
  workflow_dispatch:
#   schedule:
#   - cron: "00 07,09 * * *"  
# env:
#   TZ: "IST"
  
jobs:
  build:
    runs-on: self-hosted
    name: find-games-and-update-db
    steps:

      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
